http:
  middlewares:
    common-auth:
      basicAuth:
        usersFile: "/etc/traefik/http_auth"
    security-headers:
      headers:
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 31536000

        referrerPolicy: "same-origin"
        featurePolicy: "vibrate 'self'; geolocation 'self'; midi 'self'; notifications 'self'; push 'self'; microphone 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'; speaker 'none'; vibrate 'self'; fullscreen 'self'"

        frameDeny: false
        contentTypeNosniff: true
        browserXssFilter: true
