version: "3.7"
services:
    cnv-arena-client:
        build:
            context: ../tactic_tcg_betatest
            dockerfile: Dockerfile.client
            args:
                VITE_SERVER_URL: https://api.canvas-arena.${TRAEFIK_DOMAIN}
        container_name: cnv-arena-client
        restart: unless-stopped
        environment:
            - NODE_ENV=production
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.cnv-arena-client.loadbalancer.server.port=80"
            - "traefik.http.routers.cnv-arena-client.rule=Host(`canvas-arena.${TRAEFIK_DOMAIN}`)"
            - "traefik.http.routers.cnv-arena-client.service=cnv-arena-client"
            - "traefik.http.routers.cnv-arena-client.middlewares=security-headers@file,cnv-auth@file"
        depends_on:
            - traefik
            - cnv-arena-server

    cnv-arena-server:
        build:
            context: ../tactic_tcg_betatest
            dockerfile: Dockerfile.server
        container_name: cnv-arena-server
        restart: unless-stopped
        environment:
            - NODE_ENV=production
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.cnv-arena-server.loadbalancer.server.port=3001"
            - "traefik.http.routers.cnv-arena-server.rule=Host(`api.canvas-arena.${TRAEFIK_DOMAIN}`)"
            - "traefik.http.routers.cnv-arena-server.service=cnv-arena-server"
        depends_on:
            - traefik
