version: "3.7"
services:

    # satisfactory-server:
    #     container_name: 'satisfactory-server'
    #     image: 'wolveix/satisfactory-server:latest'
    #     environment:
    #         - AUTOPAUSE=true
    #         - MAXPLAYERS=6
    #         - PGID=${PGID}
    #         - PUID=${PUID}
    #         - SKIPUPDATE=false
    #         - STEAMBETA=false
    #         - SERVERIP=0.0.0.0
    #         - MAXTICKRATE=104857600
    #     ports:
    #         - 7777:7777/udp
    #         - 15000:15000/udp
    #         - 15777:15777/udp
    #     volumes:
    #         - satisfactory:/config
    #     restart: unless-stopped
    #     labels:
    #         - "com.centurylinklabs.watchtower1.enable=false"

    # vintagestory:
    #     image: ich777/vintagestory:latest
    #     container_name: vintagestory
    #     environment:
    #         - GAME_PARAMS=
    #         - GID=${PGID}
    #         - UID=${PUID}
    #     restart: always
    #     ports:
    #         - 42420:42420/tcp
    #     volumes:
    #         - vintageStoryConfig:/vintagestory
    #     stdin_open: true
    #     tty: true

    mc:
        container_name: 'minecraft-server'
        image: itzg/minecraft-server
        ports:
            - 25565:25565
            - 28456:28456
        environment:
            GID: ${PGID}
            UID: ${PUID}
            TZ: "${TZ}"
            # rcon #
            ENABLE_RCON: "TRUE"
            RCON_PASSWORD: "${MC_RCON_PWD}"
            RCON_PORT: 28456
            # minecraft settings #
            EULA: "TRUE"
            ENABLE_AUTOPAUSE: "TRUE"
            ONLINE_MODE: "FALSE"
            PVP: "FALSE"
            DIFFICULTY: "normal"
            # administration #
            OPS: "bibi"
            MAX_TICK_TIME: -1
            MOTD: "Minecraft Docker Server powered by Bibi"
            SNOOPER_ENABLED: "FALSE"
            SERVER_NAME: "${TRAEFIK_DOMAIN}"
            MEMORY: "8G"
            WHITELIST_FILE: "/data/extra/whitelist.json"
            ENFORCE_WHITELIST: "TRUE"
            OVERRIDE_WHITELIST : "TRUE"
            # server type & world #
            TYPE: "FABRIC"
            FABRIC_LAUNCHER_VERSION: 0.16.0
            FABRIC_LOADER_VERSION: 1.0.1
            # CF_SLUG: "bm-exosphere"
            VERSION: 1.21
            # SEED: "37021689"
            LEVEL: "vanilla_structures"
            MAX_WORLD_SIZE: 5000
            # CF_API_KEY: ${CF_API_KEY}
        restart: unless-stopped
        volumes:
            # attach a directory relative to the directory containing this compose file #
            - mcServer:/data
            - mcModPacks:/modpacks
            - mcMods:/mods
        labels:
            - "com.centurylinklabs.watchtower1.enable=false"

    rcon:
        container_name: 'rcon'
        image: itzg/rcon
        depends_on:
            - mc
        environment:
            RWA_ENV: "TRUE"
            RWA_USERNAME: "bibi"
            RWA_PASSWORD: "${RCON_PWD}"
            RWA_ADMIN: "TRUE"
            # is referring to the hostname of 'mc' compose service below #
            RWA_RCON_HOST: mc
            RWA_RCON_PORT: 28456
            # needs to match the password configured for the container, which is 'minecraft' by default #
            RWA_RCON_PASSWORD: "${MC_RCON_PWD}"
            RWA_WEBSOCKET_URL_SSL: "wss://rcon.${TRAEFIK_DOMAIN}/ws"
            RWA_WEBSOCKET_URL: "ws://rcon.${TRAEFIK_DOMAIN}/ws"
        restart: unless-stopped
        volumes:
            - rconDirectory:/opt/rcon-web-admin/db
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.rcon-web.loadbalancer.server.port=4326"
            - "traefik.http.services.rcon-ws.loadbalancer.server.port=4327"
            - "traefik.http.routers.rcon-web.rule=Host(`rcon.${TRAEFIK_DOMAIN}`)"
            - "traefik.http.routers.rcon-web.service=rcon-web"
            - "traefik.http.routers.rcon-ws.rule=Host(`rcon.${TRAEFIK_DOMAIN}`) && Path(`/ws`)"
            - "traefik.http.routers.rcon-ws.service=rcon-ws"
            # watchtower #
            - "com.centurylinklabs.watchtower1.enable=false"

    # frozen-flame:
    #     image: ghcr.io/ragingdave/frozen-flame-docker:main
    #     container_name: frozen-flame
    #     restart: unless-stopped
    #     ports:
    #         - "25575:25575"
    #         - "27015:27015"
    #         - "27015:27015/udp"
    #         - "7777:7777"
    #         - "7777:7777/udp"
    #     environment:
    #         SERVER_NAME: "Bibibox.ga: FrozenFlame dedicated server"
    #         RCON_PASSWORD: "${RCON_PWD}"
    #         ADDITIONAL_ARGS: "-noeac"
    #     volumes:
    #         - frozenFlameServer:/home/steam/frozen-flame-dedicated/FrozenFlame/Saved
    #     labels:
    #         - "com.centurylinklabs.watchtower1.enable=false"

    # valheim-plus:
    #     image: lloesche/valheim-server
    #     container_name: valheim-plus
    #     restart: unless-stopped
    #     cap_add:
    #         - sys_nice
    #     ports:
    #         - "2456-2457:2456-2457/udp"
    #     environment:
    #         PGID: "${PGID}"
    #         PUID: "${PUID}"
    #         TZ: "${TZ}"
    #         SERVER_NAME: "${VALHEIM_SV_NAME}"
    #         SERVER_PORT: "${VALHEIM_SV_PORT}"
    #         WORLD_NAME: "NewVR"
    #         BEPINEX: "true"
    #         SERVER_PUBLIC: 0
    #         SERVER_PASS: "${VALHEIM_SV_PWD}"
    #         UPDATE_IF_IDLE: "true"
    #         RESTART_CRON: ""
    #         BACKUPS_MAX_COUNT: 3
    #         UPDATE_INTERVAL: 14400
    #         VALHEIM_PLUS: "false"
    #     volumes:
    #         - valheimPlusSaves:/config
    #         - valheimPlusData:/opt/valheim
    #         - /tmp:/tmp
    #     labels:
    #         - "com.centurylinklabs.watchtower1.enable=false"

    # icarus:
    #     image: mornedhels/icarus-server:dev
    #     container_name: icarus
    #     restart: unless-stopped
    #     environment:
    #         - "SERVER_NAME=Bibibox Icarus Server"
    #         - SERVER_PASSWORD=qsdfg
    #         - SERVER_ADMIN_PASSWORD=${RCON_PWD}
    #         - SERVER_PORT=17777
    #         - SERVER_QUERYPORT=27015
    #         - PGID=${PGID}
    #         - PUID=${PUID}
    #         - CLEANUP_EXCLUDES=Housing
    #         - STEAM_API_KEY=${STEAM_API_KEY}
    #     ports:
    #         - "17777:17777/udp"
    #         - "27015:27015/udp"
    #     volumes:
    #         - icarusConfig:/home/icarus/drive_c/icarus
    #         - icarusServer:/opt/icarus

    olivetin:
        image: jamesread/olivetin
        container_name: olivetin
        restart: unless-stopped
        user: root
        volumes:
            - olivetinConfig:/config
            - /var/run/docker.sock:/var/run/docker.sock
            - /usr/bin/docker:/usr/bin/docker
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.olivetin.loadbalancer.server.port=1337"
            - "traefik.http.routers.olivetin.rule=Host(`actions.${TRAEFIK_DOMAIN}`)"
            - "traefik.http.routers.olivetin.service=olivetin"
        depends_on:
            - traefik

    # palworld:
    #     image: thijsvanloef/palworld-server-docker:latest
    #     restart: unless-stopped
    #     container_name: palworld
    #     ports:
    #         - 8211:8211/udp
    #         - 27015:27015/udp
    #     environment:
    #         - PUID=${PUID}
    #         - PGID=${PGID}
    #         - PORT=8211
    #         - SERVER_NAME=Bibibox
    #         - PLAYERS=10
    #         - MULTITHREADING=true
    #         - RCON_ENABLED=true
    #         - RCON_PORT=25575
    #         - ADMIN_PASSWORD=${GAMES_ADMIN_PASSWORD}
    #         - COMMUNITY=false
    #         - SERVER_PASSWORD=${GAMES_JOIN_PASSWORD}
    #     volumes:
    #         - palworldConfig:/palworld/

    # enshrouded:
    #     image: mornedhels/enshrouded-server:latest
    #     container_name: enshrouded
    #     hostname: enshrouded
    #     restart: unless-stopped
    #     stop_grace_period: 90s
    #     ports:
    #         - "15636-15637:15636-15637/udp"
    #     volumes:
    #         - enshroudedConfig:/opt/enshrouded
    #     environment:
    #         - BACKUP_CRON=*/15 * * * *
    #         - BACKUP_MAX_COUNT=2
    #         - SERVER_NAME=Bibibox
    #         - SERVER_PASSWORD=${ENSHROUDED_SERVER_PASSWORD}
    #         - UPDATE_CRON=*/30 * * * *
    #         - PUID=${PUID}
    #         - PGID=${PGID}
    #         - STEAM_API_PUBLIC_IP=${DOCKER_HOST_IP}
    #         - STEAM_API_KEY=${STEAM_API_KEY}

    # core-keeper:
    #     image: escaping/core-keeper-dedicated
    #     container_name: core-keeper
    #     environment:
    #         - WORLD_INDEX=0
    #         - WORLD_NAME=Bibibox Server
    #         - GAME_ID=4pHuSJPCjSXNUPk5gjPN6PpTgWqK
    #         - DATA_PATH=/home/steam/core-keeper-data
    #         - MAX_PLAYERS=10
    #         - USER=${MEDIA_USER}
    #     volumes:
    #         - coreKeeperApp:/home/steam/core-keeper-dedicated
    #         - coreKeeperData:/home/steam/core-keeper-data
    #     restart: always
    #     stop_grace_period: 2m

volumes:
    valheimPlusSaves:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/${GAMES_DIR_NAME}/valheim-server/config/
    valheimPlusData:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/${GAMES_DIR_NAME}/valheim-server/data/
    satisfactory:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/${GAMES_DIR_NAME}/satisfactory-server/
    mcServer:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/${GAMES_DIR_NAME}/minecraft-server/
    mcModPacks:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/${GAMES_DIR_NAME}/minecraft-modpacks/
    mcMods:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/${GAMES_DIR_NAME}/minecraft-mods/
    rconDirectory:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/${GAMES_DIR_NAME}/rcon/
    frozenFlameServer:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/${GAMES_DIR_NAME}/frozenFlame-server/
    icarusServer:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/${GAMES_DIR_NAME}/icarus-server/data
    icarusConfig:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/${GAMES_DIR_NAME}/icarus-server/config
    palworldConfig:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/${GAMES_DIR_NAME}/palworld/
    olivetinConfig:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/${GAMES_DIR_NAME}/olivetin/
    enshroudedConfig:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/${GAMES_DIR_NAME}/enshrouded/
    coreKeeperData:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/${GAMES_DIR_NAME}/coreKeeper/data
    coreKeeperApp:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/${GAMES_DIR_NAME}/coreKeeper/app
    vintageStoryConfig:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/${GAMES_DIR_NAME}/vintageStory