version: "3.7"

services:
#region Containers
    #region NetWork
    traefik:
        image: traefik
        container_name: traefik
        restart: always
        command:
            - "--certificatesresolvers.leresolver.acme.email=${ACME_MAIL}"
            - "--api.insecure"
            - "--pilot.token=${PILOT_TOKEN}"
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - traefikBehaviour:/etc/traefik:ro
            - configTraefik:/config
        environment:
            - TRAEFIK_DOMAIN=${TRAEFIK_DOMAIN}
            - TZ=${TZ}
        labels:
            - "traefik.enable=true"
            # Docker labels for enabling Traefik dashboard
            - "traefik.http.routers.traefik.rule=Host(`traefik.${TRAEFIK_DOMAIN}`)"
            - "traefik.http.routers.traefik.service=api@internal"
            - "traefik.http.routers.traefik.middlewares=common-auth@file"
    #endregion

    #region Streaming/Reader
    plex:
        image: linuxserver/plex
        container_name: plex
        restart: always
        ports:
            - "32400:32400"
            - "32400:32400/udp"
            - "32469:32469"
            - "32469:32469/udp"
            - "5353:5353/udp"
            - "1900:1900/udp"
        volumes:
            - configPlex:/config
            - media:/data
        environment:
            - PGID=${PGID}
            - PUID=${PUID}
            - TZ=${TZ}
            - VERSION=docker
            - PLEX_CLAIM=claim-vy7qccuF8phpRK6XV9Ft
            - ADVERTISE_IP=plex.${TRAEFIK_DOMAIN}:443
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.plex.loadbalancer.server.port=32400"
            - "traefik.http.routers.plex.rule=Host(`plex.${TRAEFIK_DOMAIN}`)"

    ubooquity:
        image: ghcr.io/linuxserver/ubooquity
        container_name: ubooquity
        environment:
            - PGID=${PGID}
            - PUID=${PUID}
            - TZ=${TZ}
            - MAXMEM=2048
        volumes:
            - configUbooquity:/config
            - books:/books
            - comics:/comics
        restart: unless-stopped
        labels:
            - "traefik.enable=true"
            # router reader - Web UI
            - "traefik.http.routers.reader.rule=Host(`reader.${TRAEFIK_DOMAIN}`)"
            - "traefik.http.services.reader.loadbalancer.server.port=2202"
            - "traefik.http.routers.reader.middlewares=common-auth@file"
            - "traefik.http.routers.reader.service=ubooquity"
            # router ubooquity - Admin UI
            - "traefik.http.routers.ubooquity.rule=Host(`ubooquity.${TRAEFIK_DOMAIN}`)"
            - "traefik.http.services.ubooquity.loadbalancer.server.port=2203"
            - "traefik.http.routers.ubooquity.middlewares=common-auth@file"
            - "traefik.http.routers.ubooquity.service=ubooquity"
    #endregion

    #region Downloader
    rutorrent:
        image: mondedie/rutorrent:latest
        container_name: rutorrent
        environment:
            - GID=${PGID}
            - UID=${PUID}
            - TZ=${TZ}
            - DHT_RTORRENT=on
            - PORT_RTORRENT=6881
        volumes:
            - configRutorrent:/config
            - torrents:/data
        restart: unless-stopped
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.rutorrent.loadbalancer.server.port=8080"
            - "traefik.http.routers.rutorrent.rule=Host(`torrent.${TRAEFIK_DOMAIN}`)"
            - "traefik.http.routers.rutorrent.middlewares=common-auth@file"

    jdownloader:
        image: jlesage/jdownloader-2
        container_name: jdownloader
        restart: unless-stopped
        volumes:
            - configJdownloader:/config
            - media:/data
        environment:
            - USER_ID=${PUID}
            - GROUP_ID=${PGID}
            - TZ=${TZ}
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.jdownloader.loadbalancer.server.port=5800"
            - "traefik.http.routers.jdownloader.rule=Host(`ddl.${TRAEFIK_DOMAIN}`)"
            - "traefik.http.routers.jdownloader.middlewares=common-auth@file"
    #endregion Downloader

    #region Cloud
    nextcloud-db:
        image: linuxserver/mariadb
        container_name: nextcloud-db
        command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
        restart: always
        environment:
            - PGID=${PGID}
            - PUID=${PUID}
            - TZ=${TZ}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        volumes:
            - nextcloudDb:/config
        labels:
            - "traefik.enable=false"

    # See init-setup-nextcloud.sh for first install
    nextcloud:
        depends_on:
            - nextcloud-db
        image: linuxserver/nextcloud
        container_name: nextcloud
        restart: always
        environment:
            - PGID=${PGID}
            - PUID=${PUID}
            - TZ=${TZ}
        volumes:
            - configNextcloud:/config
            - nextcloudData:/data
            - media:/media
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.nextcloud.rule=Host(`cloud.${TRAEFIK_DOMAIN}`)"
    #endregion Cloud

    #region Media monitors
    jackett:
        image: sclemenceau/docker-jackett:cloudproxy
        container_name: jackett
        environment:
            - PGID=${PGID}
            - PUID=${PUID}
            - TZ=${TZ}
            - JACKETT_NO_UPDATES=1
        volumes:
            - configJackett:/config
            - /etc/localtime:/etc/localtime:ro
        restart: unless-stopped
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.jackett.loadbalancer.server.port=9117"
            - "traefik.http.routers.jackett.rule=Host(`jackett.${TRAEFIK_DOMAIN}`)"
            - "traefik.http.routers.jackett.middlewares=common-auth@file"

    cloudproxy:
        image: noahcardoza/cloudproxy
        container_name: cloudproxy
        restart: unless-stopped

    medusa:
        image: ghcr.io/linuxserver/medusa
        container_name: medusa
        environment:
            - PGID=${PGID}
            - PUID=${PUID}
            - TZ=${TZ}
        volumes:
            - configMedusa:/config
            - media:/media
            - torrents:/downloads
        restart: unless-stopped
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.medusa.loadbalancer.server.port=8081"
            - "traefik.http.routers.medusa.rule=Host(`medusa.${TRAEFIK_DOMAIN}`)"
            - "traefik.http.routers.medusa.middlewares=common-auth@file"

    radarr:
        image: linuxserver/radarr
        container_name: radarr
        restart: always
        volumes:
            - configRadarr:/config
            - movies:/movies
            - torrents:/downloads
            - /etc/localtime:/etc/localtime:ro
        environment:
            - PGID=${PGID}
            - PUID=${PUID}
            - TZ=${TZ}
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.radarr.rule=Host(`movie.${TRAEFIK_DOMAIN}`)"
            - "traefik.http.routers.radarr.middlewares=common-auth@file"

    lidarr:
        image: linuxserver/lidarr
        container_name: lidarr
        restart: always
        volumes:
            - configLidarr:/config
            - musics:/musics
            - torrents:/downloads
        environment:
            - PGID=${PGID}
            - PUID=${PUID}
            - TZ=${TZ}
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.lidarr.rule=Host(`book.${TRAEFIK_DOMAIN}`)"
            - "traefik.http.routers.lidarr.middlewares=common-auth@file"

    mylar:
        image: ghcr.io/linuxserver/mylar3
        container_name: mylar
        volumes:
            - configMylar:/config
            - comics:/comics
            - torrents:/downloads
        environment:
            - PGID=${PGID}
            - PUID=${PUID}
            - TZ=${TZ}
        restart: unless-stopped
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.mylar.rule=Host(`comic.${TRAEFIK_DOMAIN}`)"
            - "traefik.http.services.mylar.loadbalancer.server.port=8090"
            - "traefik.http.routers.mylar.middlewares=common-auth@file"
    #endregion Media monitors

    #region Administration
    portainer:
        image: portainer/portainer-ce
        container_name: portainer
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - configPortainer:/data
        command: --host=unix:///var/run/docker.sock
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.portainer.rule=Host(`docker.${TRAEFIK_DOMAIN}`)"
            - "traefik.http.routers.portainer.middlewares=common-auth@file"
            - "traefik.http.services.portainer.loadbalancer.server.port=9000"

    netdata:
        image: netdata/netdata
        restart: always
        container_name: netdata
        hostname: netdata.${TRAEFIK_DOMAIN}
        environment:
            PGID: 999
        cap_add:
            - SYS_PTRACE
        security_opt:
            - apparmor:unconfined
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /var/run/docker.sock:/var/run/docker.sock:rw
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.netdata.rule=Host(`netdata.${TRAEFIK_DOMAIN}`)"
            - "traefik.http.routers.netdata.middlewares=common-auth@file"
            - "traefik.http.services.netdata.loadbalancer.server.port=19999"


    duplicati:
        image: linuxserver/duplicati
        container_name: duplicati
        restart: unless-stopped
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - configDuplicati:/config
            - backups:/backups
            - alldata:/source
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.duplicati.rule=Host(`backup.${TRAEFIK_DOMAIN}`)"
            - "traefik.http.routers.duplicati.middlewares=common-auth@file"
            - "traefiahk.http.services.duplicati.loadbalancer.server.port=8200"

    shellinabox:
        image: sspreitzer/shellinabox:latest
        container_name: shellinabox
        restart: unless-stopped
        environment:
            - SIAB_USER=${MEDIA_USER}
            - SIAB_PASSWORD=${SIAB_PASSWORD}
            - SIAB_GROUP=${MEDIA_USER}
            - SIAB_HOME=/home/{$MEDIA_USER}
            - SIAB_USERID=${PUID}
            - SIAB_GROUPID=${PGID}
            - SIAB_SUDO=true
            - SIAB_PKGS=${SIAB_PKGS}
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.shellinabox.rule=Host(`shell.${TRAEFIK_DOMAIN}`)"
            - "traefik.http.routers.shellinabox.middlewares=common-auth@file"
            - "traefik.http.services.shellinabox.loadbalancer.server.port=4200"

    organizr:
        image: organizr/organizr
        container_name: organizr
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - fpm=true
        restart: unless-stopped
        volumes:
            - configOrganizr:/config
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.organizr.rule=Host(`home.${TRAEFIK_DOMAIN}`)"
            - "traefik.http.routers.organizr.middlewares=common-auth@file"
            - "traefik.http.services.organizr.loadbalancer.server.port=80"

    sftp:
        image: netresearch/sftp
        container_name: sftp
        volumes:
            - alldata:/home/${MEDIA_USER}/upload
            - configSftp/:/etc/ssh/
        ports:
            - "${FTP_PORT}:22"
        restart: unless-stopped
        command: "${FTP_USER}:${FTP_PASSWORD}:${PUID}:${PGID}"

    openvpn:
        image: ghcr.io/linuxserver/openvpn-as
        container_name: openvpn
        cap_add:
            - NET_ADMIN
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - configOpenVPN:/config
        ports:
            - 9443:9443
            - 1194:1194/udp
        restart: unless-stopped
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.openvpn.rule=Host(`vpn.${TRAEFIK_DOMAIN}`)"
            - "traefik.http.routers.openvpn.middlewares=common-auth@file"
            - "traefik.http.services.openvpn.loadbalancer.server.port=943"


        # tautulli:
        #     image: linuxserver/tautulli
        #     container_name: tautulli
        #     restart: always
        #     volumes:
        #         - configTautulli:/config
        #         - config:/logs:ro # Inside of tautulli, bind to logs via "/logs/Plex Media Server/Logs"
        #     environment:
        #         - PGID=${PGID}
        #         - PUID=${PUID}
        #         - TZ=${TZ}
        #     labels:
        #         - "traefik.enable=true"
        #         - "traefik.http.routers.tautulli.rule=Host(`tautulli.${TRAEFIK_DOMAIN}`)"
    #endregion Administration
#endregion Containers

#region Networks
networks:
  default:
    external:
      name: "traefik-network"
#endregion Networks

#region Volumes
volumes:
    alldata:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}
    config:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/config
    #region Volumes Config
    traefikBehaviour:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/config/traefik/behaviour
    configTraefik:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/config/traefik
    configPlex:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/config/plex
    configRutorrent:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/config/rutorrent
    configMedusa:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/config/medusa
    configRadarr:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/config/radarr
    configBazarr:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/config/bazarr
    configJackett:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/config/jackett
    configLidarr:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/config/lidarr
    configMylar:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/config/mylarr
    configTautulli:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/config/tautulli
    configJdownloader:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/config/jdownloader
    nextcloudDb:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/config/nextcloud-db
    configNextcloud:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/config/nextcloud
    nextcloudData:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/config/nextcloud-data
    configPortainer:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/config/portainer
    configOrganizr:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/config/organizr
    configOpenVPN:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/config/openVPN
    configSftp:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/config/sftp
    configDuplicati:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/config/duplicati
    configUbooquity:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/config/ubooquity
    #endregion Config
    backups:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/backups
    torrents:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/torrents/
    #region Volumes Media
    media:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/media
    musics:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/media/musics
    movies:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/media/movies
    comics:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/media/books/comics
    books:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/media/books
    #endregion Media
#endregion Volumes