version: "3.7"

services:
    # odin:
    #     image: mbround18/valheim-odin:latest
    #     container_name: odin
    #     restart: unless-stopped
    #     volumes:
    #         - odin-output:/data/odin/target/release
    # valheim:
    #     # depends_on:
    #     #     - odin
    #     image: mbround18/valheim:latest
    #     container_name: valheim
    #     restart: unless-stopped
    #     ports:
    #         - 2456:2456
    #         - 2457:2457
    #         - 2458:2458
    #         - 27000-27037:27000-27037
    #         - 3478:3478
    #         - 4379:4379
    #         - 4380:4380
    #         - 2456:2456/udp
    #         - 2457:2457/udp
    #         - 2458:2458/udp
    #         - 27000-27037:27000-27037/udp
    #         - 3478:3478/udp
    #         - 4379:4379/udp
    #         - 4380:4380/udp
    #     environment:
    #         - PGID=${PGID}
    #         - PUID=${PUID}
    #         - TZ=${TZ}
    #         - NAME=${VALHEIM_SV_NAME}
    #         - WORLD=${VALHEIM_SV_WORLD}
    #         - PORT=${VALHEIM_SV_PORT}
    #         - PUBLIC=${VALHEIM_SV_PUBLIC}
    #         - PASSWORD=${VALHEIM_SV_PWD}
    #         - AUTO_UPDATE=0
    #         #- AUTO_UPDATE_SCHEDULE="0 6 * * *"
    #     volumes:
    #         - valheimSaves:/home/steam/.config/unity3d/IronGate/Valheim
    #         - valheimServer:/home/steam/valheim
    #         - /tmp:/tmp
    #         #- odin-output:/home/steam/.odin
    #     labels:
    #         - "com.centurylinklabs.watchtower1.enable=false"

    # valheim-plus:
    #     # depends_on:
    #     #     - odin
    #     image: lloesche/valheim-server
    #     container_name: valheim-plus
    #     restart: unless-stopped
    #     cap_add:
    #         - sys_nice
    #     ports:
    #         - "2456-2457:2456-2457/udp"
    #     environment:
    #         - TZ=${TZ}
    #         - SERVER_NAME=${VALHEIM_SV_NAME}
    #         - SERVER_PORT=${VALHEIM_SV_PORT}
    #         - WORLD_NAME=allin
    #         - SERVER_PUBLIC=0
    #         - SERVER_PASS=${VALHEIM_SV_PWD}
    #         - UPDATE_CRON=
    #         - RESTART_CRON=
    #         - BACKUPS=true
    #         - VALHEIM_PLUS=true
    #         - UPDATE_INTERVAL=14400
    #     volumes:
    #         - valheimPlusSaves:/config
    #         - valheimPlusData:/opt/valheim
    #         - /tmp:/tmp
    #     labels:
    #         - "com.centurylinklabs.watchtower1.enable=false"

    # satisfactory-server:
    #     container_name: 'satisfactory-server'
    #     hostname: 'satisfactory'
    #     image: 'wolveix/satisfactory-server:latest'
    #     environment:
    #         - MAXPLAYERS=8
    #         - PGID=${PGID}
    #         - PUID=${PUID}
    #         - SKIPUPDATE=false
    #         - STEAMBETA=true
    #         - SERVERIP=0.0.0.0
    #     ports:
    #         - 7777:7777/udp
    #         - 15000:15000/udp
    #         - 15777:15777/udp
    #     volumes:
    #         - satisfactory:/config
    #     restart: unless-stopped
    #     labels:
    #         - "com.centurylinklabs.watchtower1.enable=false"

    mc:
        container_name: 'minecraft-server'
        image: itzg/minecraft-server
        ports:
            - 25565:25565
        environment:
            EULA: "true"
            TZ: ${TZ}
            PGID: ${PGID}
            PUID: ${PUID}
            ENABLE_RCON: "true"
            RCON_PASSWORD: "meoo"
            RCON_PORT: 28016
            ONLINE_MODE: "false"
            PVP: "false"
            OPS: "bibi"
            SERVER_NAME: "Bibibox.ga"
            ENABLE_AUTOPAUSE: "true"
            MAX_TICK_TIME: -1
        tty: true
        stdin_open: true
        restart: unless-stopped
        volumes:
            # attach a directory relative to the directory containing this compose file
            - minecraftServer:/data
        labels:
            - "com.centurylinklabs.watchtower1.enable=false"

    rcon:
        container_name: 'rcon'
        image: itzg/rcon
        environment:
            RWA_USERNAME: bibi
            RWA_PASSWORD: azerty1234
            RWA_ADMIN: "true"
            # is referring to the hostname of 'mc' compose service above
            RWA_RCON_HOST: mc
            # needs to match the password configured for the container, which is 'minecraft' by default
            RWA_RCON_PASSWORD: meoo
        ports:
            - 4326:4326
            - 4327:4327
        restart: unless-stopped
        volumes:
            - rcon:/opt/rcon-web-admin/db
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.rcon.loadbalancer.server.port=4326"
            - "traefik.http.routers.rcon.rule=Host(`rcon.${TRAEFIK_DOMAIN}`)"
            - "traefik.http.routers.rcon.middlewares=common-auth@file"
            - "traefik.http.routers.rcon.service=rcon"

volumes:
    valheimSaves:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/${CONFIG_DIR_NAME}/valheim/saves/
    valheimServer:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/${CONFIG_DIR_NAME}/valheim/server/
    valheimPlusSaves:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/${CONFIG_DIR_NAME}/valheim-server/config/
    valheimPlusData:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/${CONFIG_DIR_NAME}/valheim-server/data/
    # odin-output:
    #     driver: local-persist
    #     driver_opts:
    #         mountpoint: ${BASE_PATH}/${CONFIG_DIR_NAME}/valheim/odin/
    satisfactory:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/${CONFIG_DIR_NAME}/satisfactory-server/
    minecraftServer:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/${CONFIG_DIR_NAME}/minecraft-server/
    rcon:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/${CONFIG_DIR_NAME}/rcon/
    #enregion games