version: "3.7"
services:

    # satisfactory-server:
    #     container_name: 'satisfactory-server'
    #     hostname: 'satisfactory'
    #     image: 'wolveix/satisfactory-server:latest'
    #     environment:
    #         - MAXPLAYERS=8
    #         - PGID=${PGID}
    #         - PUID=${PUID}
    #         - SKIPUPDATE=false
    #         - STEAMBETA=true
    #         - SERVERIP=0.0.0.0
    #     ports:
    #         - 7777:7777/udp
    #         - 15000:15000/udp
    #         - 15777:15777/udp
    #     volumes:
    #         - satisfactory:/config
    #     restart: unless-stopped
    #     labels:
    #         - "com.centurylinklabs.watchtower1.enable=false"

    # mc:
    #     container_name: 'minecraft-server'
    #     image: itzg/minecraft-server
    #     ports:
    #         - 25565:25565
    #         - 28456:28456
    #     environment:
    #         GID: ${PGID}
    #         UID: ${PUID}
    #         # rcon #
    #         ENABLE_RCON: "TRUE"
    #         RCON_PASSWORD: "${MC_RCON_PWD}"
    #         RCON_PORT: 28456
    #         # minecraft settings #
    #         EULA: "TRUE"
    #         ENABLE_AUTOPAUSE: "TRUE"
    #         ONLINE_MODE: "FALSE"
    #         PVP: "FALSE"
    #         DIFFICULTY: "normal"
    #         # administration #
    #         OPS: "bibi"
    #         MAX_TICK_TIME: -1
    #         MOTD: "Minecraft Docker Server powered by Bibi"
    #         SNOOPER_ENABLED: "FALSE"
    #         SERVER_NAME: "Bibibox.ga"
    #         MEMORY: "8G"
    #         WHITELIST_FILE: "/data/extra/whitelist.json"
    #         ENFORCE_WHITELIST: "TRUE"
    #         OVERRIDE_WHITELIST : "TRUE"
    #         # server type & world #
    #         TYPE: "CURSEFORGE"
    #         CF_SERVER_MOD: "/modpacks/Better_MC_FABRIC_Server_Pack_1.19.2_v12.5.zip"
    #         VERSION: 1.19.2
    #         SEED: "37021689"
    #         LEVEL: "betterMC"
    #         MAX_WORLD_SIZE: 5000
    #     restart: unless-stopped
    #     volumes:
    #         # attach a directory relative to the directory containing this compose file #
    #         - mcServer:/data
    #         - mcModPacks:/modpacks
    #     labels:
    #         - "com.centurylinklabs.watchtower1.enable=false"

    # rcon:
    #     container_name: 'rcon'
    #     image: itzg/rcon
    #     depends_on:
    #         - mc
    #     environment:
    #         RWA_ENV: "TRUE"
    #         RWA_USERNAME: "bibi"
    #         RWA_PASSWORD: "${RCON_PWD}"
    #         RWA_ADMIN: "TRUE"
    #         # is referring to the hostname of 'mc' compose service below #
    #         RWA_RCON_HOST: mc
    #         RWA_RCON_PORT: 28456
    #         # needs to match the password configured for the container, which is 'minecraft' by default #
    #         RWA_RCON_PASSWORD: "${MC_RCON_PWD}"
    #         RWA_WEBSOCKET_URL_SSL: "wss://rcon.${TRAEFIK_DOMAIN}/ws"
    #         RWA_WEBSOCKET_URL: "ws://rcon.${TRAEFIK_DOMAIN}/ws"
    #     restart: unless-stopped
    #     volumes:
    #         - rconDirectory:/opt/rcon-web-admin/db
    #     labels:
    #         - "traefik.enable=true"
    #         - "traefik.http.services.rcon-web.loadbalancer.server.port=4326"
    #         - "traefik.http.services.rcon-ws.loadbalancer.server.port=4327"
    #         - "traefik.http.routers.rcon-web.rule=Host(`rcon.${TRAEFIK_DOMAIN}`)"
    #         - "traefik.http.routers.rcon-web.service=rcon-web"
    #         - "traefik.http.routers.rcon-ws.rule=Host(`rcon.${TRAEFIK_DOMAIN}`) && Path(`/ws`)"
    #         - "traefik.http.routers.rcon-ws.service=rcon-ws"
    #         # watchtower #
    #         - "com.centurylinklabs.watchtower1.enable=false"

    # odin:
    #     image: mbround18/valheim-odin:latest
    #     container_name: odin
    #     restart: unless-stopped
    #     volumes:
    #         - odin-output:/data/odin/target/release
    # valheim:
    #     # depends_on:
    #     #     - odin
    #     image: mbround18/valheim:latest
    #     container_name: valheim
    #     restart: unless-stopped
    #     ports:
    #         - 2456:2456
    #         - 2457:2457
    #         - 2458:2458
    #         - 27000-27037:27000-27037
    #         - 3478:3478
    #         - 4379:4379
    #         - 4380:4380
    #         - 2456:2456/udp
    #         - 2457:2457/udp
    #         - 2458:2458/udp
    #         - 27000-27037:27000-27037/udp
    #         - 3478:3478/udp
    #         - 4379:4379/udp
    #         - 4380:4380/udp
    #     environment:
    #         - PGID=${PGID}
    #         - PUID=${PUID}
    #         - TZ=${TZ}
    #         - NAME=${VALHEIM_SV_NAME}
    #         - WORLD=${VALHEIM_SV_WORLD}
    #         - PORT=${VALHEIM_SV_PORT}
    #         - PUBLIC=${VALHEIM_SV_PUBLIC}
    #         - PASSWORD=${VALHEIM_SV_PWD}
    #         - AUTO_UPDATE=0
    #         #- AUTO_UPDATE_SCHEDULE="0 6 * * *"
    #     volumes:
    #         - valheimSaves:/home/steam/.config/unity3d/IronGate/Valheim
    #         - valheimServer:/home/steam/valheim
    #         - /tmp:/tmp
    #         #- odin-output:/home/steam/.odin
    #     labels:
    #         - "com.centurylinklabs.watchtower1.enable=false"

    valheim-plus:
        image: lloesche/valheim-server
        container_name: valheim-plus
        restart: unless-stopped
        cap_add:
            - sys_nice
        ports:
            - "2456-2457:2456-2457/udp"
        environment:
            PGID: "${PGID}"
            PUID: "${PUID}"
            TZ: "${TZ}"
            SERVER_NAME: "${VALHEIM_SV_NAME}"
            SERVER_PORT: "${VALHEIM_SV_PORT}"
            WORLD_NAME: "NewVR"
            BEPINEX: true
            SERVER_PUBLIC: 0
            SERVER_PASS: "${VALHEIM_SV_PWD}"
            UPDATE_IF_IDLE: "TRUE"
            RESTART_CRON: ""
            BACKUPS_MAX_COUNT: 3
            UPDATE_INTERVAL: 14400
            VALHEIM_PLUS: "FALSE"
        volumes:
            - valheimPlusSaves:/config
            - valheimPlusData:/opt/valheim
            - /tmp:/tmp
        labels:
            - "com.centurylinklabs.watchtower1.enable=false"

    frozen-flame:
        image: ghcr.io/ragingdave/frozen-flame-docker:main
        container_name: frozen-flame
        restart: unless-stopped
        ports:
            - "25575:25575"
            - "27015:27015"
            - "27015:27015/udp"
            - "7777:7777"
            - "7777:7777/udp"
        environment:
            SERVER_NAME: "Bibibox.ga: FrozenFlame dedicated server"
            RCON_PASSWORD: "${RCON_PWD}"
            ADDITIONAL_ARGS: "-noeac"
        volumes:
            - frozenFlameServer:/home/steam/frozen-flame-dedicated/FrozenFlame/Saved
        labels:
            - "com.centurylinklabs.watchtower1.enable=false"


volumes:
    valheimSaves:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/${CONFIG_DIR_NAME}/valheim/saves/
    valheimServer:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/${CONFIG_DIR_NAME}/valheim/server/
    valheimPlusSaves:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/${CONFIG_DIR_NAME}/valheim-server/config/
    valheimPlusData:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/${CONFIG_DIR_NAME}/valheim-server/data/
    # odin-output:
    #     driver: local-persist
    #     driver_opts:
    #         mountpoint: ${BASE_PATH}/${CONFIG_DIR_NAME}/valheim/odin/
    satisfactory:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/${CONFIG_DIR_NAME}/satisfactory-server/
    mcServer:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/${CONFIG_DIR_NAME}/minecraft-server/
    mcModPacks:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/${CONFIG_DIR_NAME}/minecraft-modpacks/
    rconDirectory:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/${CONFIG_DIR_NAME}/rcon/
    frozenFlameServer:
        driver: local-persist
        driver_opts:
            mountpoint: ${BASE_PATH}/${CONFIG_DIR_NAME}/frozenFlame-server/

