api:
  dashboard: true

# Set Access logs timezone
accessLog:
  fields:
    names:
      StartUTC: drop

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    network: "traefik-network"
    exposedByDefault: false # Only expose explicitly enabled containers
  file:
    directory: /etc/traefik/custom
    watch: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: leresolver
      middlewares:
        - security-headers@file
  openvpn:
    address: ":1194/udp"

# Allow self-signed certificates for https backends (nextcloud for example)
serversTransport:
  insecureSkipVerify: true

certificatesResolvers:
  leresolver:
    acme:
      storage: /config/acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: web
